### ISSUE TITLE
3/17 patches

### ISSUE THREAD

**Issue by waicool20** [mrmin123/kancolle-auto#340] opened 2017-03-17 09:09 UTC
Patch released today will require several updates on the script:

- Expeditions UI has changed greatly:
  - Flagship, levels and daihatsu/drum indicators have been added.
  - Expedition start button has changed
- Fleet presets increased to maximum of 10, so that needs to be implemented. Probably not gonna affect the script but the save/delete button were moved farther away from each other. Save button removed in the expand menu.

Edit:
Forgot to mention sortie UI has also changed, they added level indicators which may or may not interfere with the current reading of the ship girls statuses

**Comment by stackhanovets** [comment] 2017-03-17 09:47
Well yeah. There is a bunch of new buttons. Android interface is updated too, so there is no fun with Bluestacks/FreeBSD. Good luck @mrmin123 !

![new](https://cloud.githubusercontent.com/assets/16455270/24037487/0b09ca46-0b0f-11e7-9ba1-4d4cf9e6f94a.png)

**Comment by AppleBoi86** [comment] 2017-03-17 10:57
Some image changes in today's update.

sortie_combat.png
http://i.imgur.com/RxoRQuP.png

sortie_top_combat.png
http://i.imgur.com/pLEav08.png

combat.png (in combat folder)
http://i.imgur.com/CtYRYb4.png

combat_start.png (in combat folder)
http://i.imgur.com/36XhdcY.png

b.png (in quest folder)
http://i.imgur.com/jRbNZFV.png

ensei_start.png (in exped folder)
http://i.imgur.com/IQL90TD.png

All the changes I noticed.  No problem on expedition part.

**Comment by mrmin123** [comment] 2017-03-17 16:12
I quickly threw up a WIP branch with some of the updated assets before heading out to work: [340_patch](https://github.com/mrmin123/kancolle-auto/tree/340_patch)

Expeditions, PvP, and Quests, are working I believe. Sorties _should_ work but I'm a bit concerned about the new 'Lv.' indicator that might affect fatigue and damage-state identification... Will finalize later.

edit: fleet comp switcher might be broken due to new button placements? Unknown.

**Comment by waicool20** [comment] 2017-03-17 16:13
Cool and just before I went to bed. I'll test this overnight.

**Comment by mrmin123** [comment] 2017-03-17 16:22
* Fleet comp switcher shouldn't be broken, judging by the code, but untested.
* No separate LBAS sortie button now?? Only tested by comparing the sortie button for 6-4... I could be wrong tho.
* Damage detection seems to be working despite the Lv marker. I only had a moderate and light damaged to test again, but they both hit 1.00 on the match. Critical damage and fatigue still untested.

**Comment by waicool20** [comment] 2017-03-17 16:27
There are some problems with LBAS right now and a fix is coming hot soon, so there maybe furthur UI changes down the line. (Airplanes getting deleted for some reason)

And btw it would seem the script is having trouble dealing with ships under repair when going for a sortie, keeps on recovering... I'll test this furthur.

**Comment by waicool20** [comment] 2017-03-17 16:29
Otoh fleet comp isn't broken but idk if you plan on expanding support to the new 10 limit.

**Comment by mrmin123** [comment] 2017-03-17 16:29
OK, thanks for the heads up. I'll try testing sorties a bit later myself, too.

**Comment by mrmin123** [comment] 2017-03-17 16:31
I think I ever only made it to support the first 4 or 5 presets in the fleet comp switcher lol... I didn't have any of the slots expanded at the time of implementation =_= I'll probably expand on that at a later date in a separate ticket..

**Comment by mrmin123** [comment] 2017-03-17 16:34
Oh, combat with under-repair ships are broken because `combat_start_disabled.png` hasn't been updated... working on it now.

edit: fixed now in WIP branch

**Comment by waicool20** [comment] 2017-03-17 16:49
Ok quest ```b.png``` also has to be updated since they changed the plane pretty much game-wide

**Comment by mrmin123** [comment] 2017-03-17 16:51
`b.png` should already have been updated on the branch with this:
![b](https://cloud.githubusercontent.com/assets/4326866/24053741/3df78212-0af7-11e7-8a32-9cde4b664388.png)

Or does this image not work? I've not tested combat quests yet.

**Comment by waicool20** [comment] 2017-03-17 16:53
Oh my bad, was looking at the wrong branch. The script seems to working great now :)

**Comment by etcet54** [comment] 2017-03-18 00:00
It seems the expedition still have issues. After checking expedition status before sending the fleet, the script is automatically loop recovering and start all over again

![31239nf34h6](https://cloud.githubusercontent.com/assets/19471603/24066796/2fed7760-0ba8-11e7-8599-433d1e56e2b8.jpg)

**Comment by Bararun** [comment] 2017-03-18 00:13
Thanks for the quick update even if it's just a WIP.

**Comment by mrmin123** [comment] 2017-03-18 00:22
@stackhanovets good to know! Good news is that I've been running the sortie module for the last few hours and things seem stable.

@etcet54 Are you on the [340_patch WIP branch](https://github.com/mrmin123/kancolle-auto/tree/340_patch)? Your script is failing to find `ensei_start.png`, which was changed in the last Kantai Collection update. `master` currently does not support this, although I will be updating it shortly.

@Bararun no problem! Changes are going into `master` shortly.

**Comment by mrmin123** [comment] 2017-03-18 00:32
After some fumbling with PRs and releases, `master` has been updated. Leaving this open for a bit in case I missed anything.

**Comment by Bararun** [comment] 2017-03-18 02:49
Old 420 patch seemed to work quite well but the new master you released is seemingly looping continously and never launches expedition 6, which is the first one I have set.

**Comment by R-Jimenez** [comment] 2017-03-18 03:29
I'm seeing some issues with PvP fleet preset not being properly loaded. Could this be due to the saved fleet changes?

**Comment by etcet54** [comment] 2017-03-18 03:34
@mrmin123 yes I was using 340_patch WIP. Will check the latest master update again, thanks a lot

**Comment by R-Jimenez** [comment] 2017-03-18 16:54
Definitely seems to be something wrong with the fleet comp switching, or at least within the PvP module. Seems to go to the comp screen but unable to switch.

**Comment by mrmin123** [comment] 2017-03-18 17:35
@Bararun @etcet54 sorry for getting back so late but I can't reproduce expedition 6 not starting. Latest `master` ran fine all night.

@R-Jimenez Fleet comp switcher is independent of PvP, and PvP has been running fine for the last day for me, so I'm guessing something wrong with the fleet comp switcher module. I'll try to debug today.

**Comment by etcet54** [comment] 2017-03-19 05:34
@mrmin123 I have tested for a day and can confirm expedition works perfectly now.
I didn't experience expedition 6 not starting, so can't really speak for that one.

Thanks a lot

**Comment by stackhanovets** [comment] 2017-03-19 07:58
In my case, the 6th expedition has been set properly even on 02bbe98 ver.

![6](https://cloud.githubusercontent.com/assets/16455270/24079170/fac12924-0c92-11e7-98d3-81782f587600.png)

**Comment by waicool20** [comment] 2017-03-19 08:13
I'd say that increasing the sleep modifier might help with all these problems, at least that's what I do. Since there hasn't been much change script code wise, I don't think it's a bug within the script.

**Comment by AppleBoi86** [comment] 2017-03-19 15:45
What do I need to change to make the click box smaller?  
Since the sortie/expe button has been changed to be smaller.  It will now click outside the target area and fail to start the expedition.

**Comment by mrmin123** [comment] 2017-03-19 16:01
@AppleBoi86 just updating the image asset should do it. kancolle-auto clicks anywhere within the match itself.

Also, regarding most other issues (excluding maybe the fleet comp switcher, since I haven't tested that yet), what @waicool20 said is correct. The game did not change much, nor did the script, and it's stable for a lot of people. Incidental/sporadic issues can probably be addressed by restarting or increasing the SleepModifier in the config.

**Comment by stackhanovets** [comment] 2017-03-19 16:03
@AppleBoi86 ,
I don't realize what do you mean by "targeting issue", but I have performed some resizing tricks during events (e.g. banner changes after last kills etc) like: 
![big](https://cloud.githubusercontent.com/assets/16455270/24082385/d22d2e16-0cd5-11e7-8803-9789e8c43f5b.png) -> ![small](https://cloud.githubusercontent.com/assets/16455270/24082386/d93b4148-0cd5-11e7-9155-b4070f2c63c5.png)
That worked fine in all cases, I haven't noticed clicks outside the template.

**Comment by R-Jimenez** [comment] 2017-03-20 01:31
@mrmin123 Yeah, the PvP works fine. The exercises are properly executed, and handed off to the other modules. But the issue is that the fleet switcher isn't switching to the PvP fleet comp, so my training/victories are in mortal danger. D:

Also, don't know if it's been documented, but I the submarine switcher seems to be a bit too zealous. I have my list specified as `ss, i-19-kai, i-26-kai, i-58-kai`, but I-13/I-14 are still being pulled off the bench. Is this because of what we had to do before with stripping planes and any AA/ASW stat boosters off of them? Is a sub without those stats considered an SS when the group flag is used in the list like above?

**Comment by mrmin123** [comment] 2017-03-20 01:39
I13 and i14 should not be switched in with that configuration. If they are,
it is a bug. Stats were only relevant for identifying if the ship to be
switched out was a sub, not for identifying whether or not the ship to be
replaced with was the sub. If you didn't have I13 or i14 in your fleet to
begin with and theyre getting pulled in, that is a bug.

**Comment by NanjoW** [comment] 2017-03-20 04:40
Another thing that I've noticed is that Moral isn't tracked correctly on Married Ships due to the ring blocking the indicator.

**Comment by R-Jimenez** [comment] 2017-03-20 20:15
@mrmin123 Understood. Would you like me to make separate issues for these bugs?

**Comment by mrmin123** [comment] 2017-03-20 20:55
@R-Jimenez yes please

**Closed as completed** 2017-03-27 00:17 UTC
