### ISSUE TITLE
Iku is in trouble!

### ISSUE THREAD

**Issue by stackhanovets** [mrmin123/kancolle-auto#204] opened 2016-07-29 14:58 UTC
Why I-19 is not considered as a submarine? The script just ignores mah best sub on 55 lvl!

**Comment by mrmin123** [comment] 2016-08-09 02:01
I'll have to check myself whether or not I-19 is not being selected... if you only have one there might be an issue with the sub being on a part of the screen that doesn't match well with the sub ID image match... Does it ever click on I-19 to at least check whether or not it's a submarine?

**Comment by stackhanovets** [comment] 2016-08-12 18:03
Thank you for the response,
At last I've noticed some changes of I-19's XP.
It seems the script utilized it succesfully, at final iteration of other 6 subs, btw. 
You know, other subs have gained 50-53 lvl already when the lesser I-19 is still on lvl 3 where I've put her.

**Comment by mrmin123** [comment] 2016-08-12 18:32
I'm away from the game right now but it's entirely possible that I-19 is chosen less often just because of where she is in the ship list... is she one of the later-listed ships?

**Comment by stackhanovets** [comment] 2016-08-13 15:50
@mrmin123 Nope, but you've got the point.
The script sorts ships by type, right?
I-19 isn't the last. She is very first, here is the problem
All other SS starting from I-168 are using normally.

![2016-08-13-18-41-07](https://cloud.githubusercontent.com/assets/16455270/17644128/8854e6bc-6186-11e6-813b-355279d13d1d.png)

**Comment by mrmin123** [comment] 2016-08-13 20:28
@stackhanovets That's most likely just a side-effect of Sikuli's find all behavior. Once it finds the matches (including I-19), it sorts by highest match %, descending. When I was developing the sub switcher I noticed that the first few submarines on each page are actually processed _last_ due to this, and that's probably what you're seeing as well. If you really want your I-19s to get leveled you can use the method [here](https://github.com/mrmin123/kancolle-auto/issues/182#issuecomment-225380943) to select just I-19s.

Closing as this is not a bug, just non-obvious behavior exhibited by the script and Sikuli.

**Closed as completed by mrmin123** 2016-08-13 20:28 UTC
