### ISSUE TITLE
K-auto stuck on event boss intro screen.

### ISSUE THREAD

**Issue by AppleBoi86** [mrmin123/kancolle-auto#207] opened 2016-08-13 20:13 UTC
#### Environment details
- kancolle-auto version (last modified date): The version before current update.
- Viewer/browser: KCV
- Operating system: VISTA
#### Issue

Is the issue consistent (can be reproduced consistently) or is it transient (only happens sometimes)? Please check one of the boxes:
- [ ] Consistent
- [x] Transient

I'm running Nimu farm (E1) but sometimes auto will just stuck at the boss intro scene until I clicked on something and auto isn't showing any errors, just stuck at Selecting Fleet Formation line with the boss intro screen.

**Comment by mrmin123** [comment] 2016-08-13 20:40
Does the boss intro come up before the formation select? Before it was after formation select, and kancolle-auto is currently wired up to only deal with that.

**Comment by Zylphex** [comment] 2016-08-13 21:32
It comes before the formation select screen.

**Comment by mrmin123** [comment] 2016-08-13 21:54
Could someone provide an image? I think a image match check might be necessary here.

**Comment by Zylphex** [comment] 2016-08-13 22:11
http://i.imgur.com/Y8t8oN9.png

Here you go mrmin :)

**Comment by mrmin123** [comment] 2016-08-13 23:42
@Zylphex thanks!

This is completely untested code but please try this branch: [207_preboss_screen](https://github.com/mrmin123/kancolle-auto/tree/207_preboss_screen)

**Comment by AppleBoi86** [comment] 2016-08-14 01:32
Before?  It is **after** the formation selection for me.  Auto works fine for the first few sorties, about 5-6 sorties.  Only then it decides to get stuck on the boss intro scene.  

What do I need to change to delay the random single click after formation selection for 1-2 seconds.

**Comment by stackhanovets** [comment] 2016-08-14 08:02
Well, this one is confirmed. We need an additional click just if we are on BOSS node or on the LAST of required nodes, no need in Sikuli's recognition, e.g.:
1. The fleet has cleared 3/4 node;
2. Spinning compass, going to 4/4 node;
3. Selecting fleet formation;
4. MAGIC CLICK COMES HERE (after 2-5 seconds, no need to wait it too much due to safety);
5. Waiting for results screen.

**Comment by mrmin123** [comment] 2016-08-14 10:42
FWIW, the master branch already clicks the game screen after ~5 seconds after EVERY formation select. This behavior was added in specifically to deal with boss dialogs during the last event, and it didn't have an issue then...

**Comment by lainconnue** [comment] 2016-08-14 10:53
Now this is odd, i also have the same issue, it seems the first few sorties work fine and then somehow gets stuck at boss dialogue later (it was the 5th sortie for me). Don't know if this helps but here's the log
[2016-08-14 19:18:12] Continuing on to next node...
[log] CLICK on L(298,340)@S(0)[0,0 1366x768]
[log] CLICK on L(468,316)@S(0)[0,0 1366x768]
[2016-08-14 19:18:36] Spinning compass!
[log] CLICK on L(615,434)@S(0)[0,0 1366x768]
[2016-08-14 19:19:07] Selecting fleet formation!
[log] CLICK on L(483,368)@S(0)[0,0 1366x768]
[2016-08-14 19:20:15] Checking fleet condition...
[2016-08-14 19:20:24] Light damage: 0; moderate damage: 0; critical damage: 0
[log] CLICK on L(277,424)@S(0)[0,0 1366x768]
[2016-08-14 19:20:42] Continuing on to next node...
[log] CLICK on L(300,300)@S(0)[0,0 1366x768]
[log] CLICK on L(410,279)@S(0)[0,0 1366x768]
[2016-08-14 19:21:08] Selecting fleet formation!
[log] CLICK on L(176,410)@S(0)[0,0 1366x768]
[2016-08-14 19:22:16] Checking fleet condition...
[2016-08-14 19:22:25] Light damage: 0; moderate damage: 0; critical damage: 0
[log] CLICK on L(243,303)@S(0)[0,0 1366x768]
[2016-08-14 19:22:45] Continuing on to next node...
[log] CLICK on L(251,317)@S(0)[0,0 1366x768]
[log] CLICK on L(408,525)@S(0)[0,0 1366x768]
[2016-08-14 19:23:09] Spinning compass!
[log] CLICK on L(683,424)@S(0)[0,0 1366x768]
[2016-08-14 19:23:41] Selecting fleet formation!
[2016-08-14 19:25:01] Commencing night battle!
[log] CLICK on L(472,355)@S(0)[0,0 1366x768]
[log] CLICK on L(317,376)@S(0)[0,0 1366x768]
[2016-08-14 19:25:51] Checking fleet condition...
[2016-08-14 19:25:57] Light damage: 0; moderate damage: 2; critical damage: 0
[log] CLICK on L(647,189)@S(0)[0,0 1366x768]
[log] CLICK on L(285,213)@S(0)[0,0 1366x768]
[2016-08-14 19:26:28] Sortie complete!
[2016-08-14 19:26:28] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:26:36] At Home!
[2016-08-14 19:26:36] Checking for returning expeditions!
[2016-08-14 19:26:36] Are there returning expeditions to receive?
[log] CLICK on L(713,234)@S(0)[0,0 1366x768]
[log] CLICK on L(421,163)@S(0)[0,0 1366x768]
[2016-08-14 19:26:46] Yes, an expedition has returned!
[2016-08-14 19:26:46] It's probably fleet 4 that returned!
[log] CLICK on L(354,449)@S(0)[0,0 1366x768]
[2016-08-14 19:26:52] Are there returning expeditions to receive?
[2016-08-14 19:26:55] No, no fleets to receive!
[2016-08-14 19:26:55] Lets resupply fleets!
[2016-08-14 19:26:58] Navigating to resupply screen with 1 sidestep(s)!
[log] CLICK on L(172,301)@S(0)[0,0 1366x768]
[log] CLICK on L(41,286)@S(0)[0,0 1366x768]
[log] CLICK on L(122,198)@S(0)[0,0 1366x768]
[log] CLICK on L(244,204)@S(0)[0,0 1366x768]
[log] CLICK on L(119,203)@S(0)[0,0 1366x768]
[2016-08-14 19:27:15] Done resupplying!
[2016-08-14 19:27:15] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:27:30] Going home with 1 or less sidestep(s)!
[log] CLICK on L(566,142)@S(0)[0,0 1366x768]
[log] CLICK on L(24,523)@S(0)[0,0 1366x768]
[log] CLICK on L(66,529)@S(0)[0,0 1366x768]
[2016-08-14 19:27:49] At Home!
[2016-08-14 19:27:49] Are there returning expeditions to receive?
[2016-08-14 19:27:52] No, no fleets to receive!
[2016-08-14 19:27:53] Navigating to repair screen with 0 sidestep(s)!
[log] CLICK on L(155,477)@S(0)[0,0 1366x768]
[2016-08-14 19:27:58] Got valid timer (01:14:14)!
[2016-08-14 19:27:58] Got valid timer (00:55:50)!
[2016-08-14 19:27:59] Got valid timer (01:27:44)!
[2016-08-14 19:27:59] Attempting to conduct repairs on 2 ship(s)!
[2016-08-14 19:27:59] Available docks: 1; repair queue: 1
[log] CLICK on L(272,244)@S(0)[0,0 1366x768]
[2016-08-14 19:28:04] Check for critically damaged ships.
[2016-08-14 19:28:07] Check for moderately-damaged ships.
[log] CLICK on L(431,347)@S(0)[0,0 1366x768]
[2016-08-14 19:28:08] Starting repair on moderately damaged ship!
[2016-08-14 19:28:09] Using bucket for all repairs!
[log] CLICK on L(740,376)@S(0)[0,0 1366x768]
[log] CLICK on L(645,513)@S(0)[0,0 1366x768]
[log] CLICK on L(499,478)@S(0)[0,0 1366x768]
[2016-08-14 19:28:30] 1 ships needing repairs left...
[2016-08-14 19:28:30] Available docks: 1; repair queue: 1
[log] CLICK on L(233,259)@S(0)[0,0 1366x768]
[2016-08-14 19:28:36] Check for critically damaged ships.
[2016-08-14 19:28:39] Check for moderately-damaged ships.
[log] CLICK on L(642,351)@S(0)[0,0 1366x768]
[2016-08-14 19:28:40] Starting repair on moderately damaged ship!
[2016-08-14 19:28:42] Using bucket for all repairs!
[log] CLICK on L(740,376)@S(0)[0,0 1366x768]
[log] CLICK on L(628,513)@S(0)[0,0 1366x768]
[log] CLICK on L(553,473)@S(0)[0,0 1366x768]
[2016-08-14 19:28:47] 0 ships needing repairs left...
[2016-08-14 19:28:47] Lets resupply fleets!
[2016-08-14 19:28:54] Navigating to resupply screen with 1 sidestep(s)!
[log] CLICK on L(38,327)@S(0)[0,0 1366x768]
[log] CLICK on L(32,271)@S(0)[0,0 1366x768]
[log] CLICK on L(125,207)@S(0)[0,0 1366x768]
[log] CLICK on L(244,207)@S(0)[0,0 1366x768]
[log] CLICK on L(128,208)@S(0)[0,0 1366x768]
[2016-08-14 19:29:11] Done resupplying!
[2016-08-14 19:29:11] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:29:27] Going home with 1 or less sidestep(s)!
[log] CLICK on L(380,142)@S(0)[0,0 1366x768]
[log] CLICK on L(68,541)@S(0)[0,0 1366x768]
[2016-08-14 19:29:39] At Home!
[2016-08-14 19:29:39] Are there returning expeditions to receive?
[2016-08-14 19:29:42] No, no fleets to receive!
[2016-08-14 19:29:42] Next sortie!: 2016-08-14 19:28:43
[2016-08-14 19:29:42] -----
[2016-08-14 19:29:42] Next expedition at 2016-08-14 19:16:06 (~3 expeditions conducted)
[2016-08-14 19:29:42] Next sortie at 2016-08-14 19:28:43 (~4 sorties conducted)
[2016-08-14 19:29:42] Next scheduled sleep at 2016-08-15 00:59:00
[2016-08-14 19:29:42] -----
[2016-08-14 19:29:58] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:30:06] At Home!
[2016-08-14 19:30:06] Checking for returning expeditions!
[2016-08-14 19:30:06] Are there returning expeditions to receive?
[2016-08-14 19:30:09] No, no fleets to receive!
[2016-08-14 19:30:09] Navigating to expedition menu with 1 sidestep(s)!
[log] CLICK on L(203,320)@S(0)[0,0 1366x768]
[log] CLICK on L(403,415)@S(0)[0,0 1366x768]
[log] CLICK on L(740,202)@S(0)[0,0 1366x768]
[2016-08-14 19:30:25] Let's send fleet 4 out for expedition 5!
[log] CLICK on L(315,388)@S(0)[0,0 1366x768]
[log] CLICK on L(690,526)@S(0)[0,0 1366x768]
[2016-08-14 19:30:31] Trying to send out fleet 4 for expedition 5
[log] CLICK on L(450,209)@S(0)[0,0 1366x768]
[2016-08-14 19:30:35] Checking expedition fleet status!
[log] CLICK on L(579,513)@S(0)[0,0 1366x768]
[2016-08-14 19:30:42] Expedition sent!: Expedition 5 (ETA 2016-08-14 20:59:57)
[2016-08-14 19:30:51] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:31:07] Going home with 1 or less sidestep(s)!
[log] CLICK on L(346,138)@S(0)[0,0 1366x768]
[log] CLICK on L(48,531)@S(0)[0,0 1366x768]
[2016-08-14 19:31:15] At Home!
[2016-08-14 19:31:15] Are there returning expeditions to receive?
[log] CLICK on L(504,491)@S(0)[0,0 1366x768]
[log] CLICK on L(602,263)@S(0)[0,0 1366x768]
[2016-08-14 19:31:26] Yes, an expedition has returned!
[2016-08-14 19:31:26] It's probably fleet 2 that returned!
[log] CLICK on L(342,209)@S(0)[0,0 1366x768]
[2016-08-14 19:31:31] Are there returning expeditions to receive?
[2016-08-14 19:31:34] No, no fleets to receive!
[2016-08-14 19:31:34] Lets resupply fleets!
[2016-08-14 19:31:38] Navigating to resupply screen with 0 sidestep(s)!
[log] CLICK on L(98,302)@S(0)[0,0 1366x768]
[log] CLICK on L(178,205)@S(0)[0,0 1366x768]
[log] CLICK on L(119,201)@S(0)[0,0 1366x768]
[2016-08-14 19:31:48] Done resupplying!
[2016-08-14 19:31:48] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:32:04] Going home with 1 or less sidestep(s)!
[log] CLICK on L(26,289)@S(0)[0,0 1366x768]
[log] CLICK on L(75,339)@S(0)[0,0 1366x768]
[2016-08-14 19:32:14] At Home!
[2016-08-14 19:32:14] Are there returning expeditions to receive?
[2016-08-14 19:32:17] No, no fleets to receive!
[2016-08-14 19:32:17] Navigating to combat menu with 1 sidestep(s)!
[log] CLICK on L(235,346)@S(0)[0,0 1366x768]
[log] CLICK on L(401,321)@S(0)[0,0 1366x768]
[log] CLICK on L(566,205)@S(0)[0,0 1366x768]
[log] CLICK on L(692,514)@S(0)[0,0 1366x768]
[log] CLICK on L(618,290)@S(0)[0,0 1366x768]
[log] CLICK on L(160,319)@S(0)[0,0 1366x768]
[log] CLICK on L(671,337)@S(0)[0,0 1366x768]
[log] CLICK on L(648,534)@S(0)[0,0 1366x768]
[2016-08-14 19:32:58] Checking fleet condition...
[2016-08-14 19:33:04] Light damage: 0; moderate damage: 1; critical damage: 0
[2016-08-14 19:33:10] Checking fleet morale!
[2016-08-14 19:33:16] Ships have good morale!
[2016-08-14 19:33:16] Ships (1) in condition below repair threshold! Sortie cancelled!
[2016-08-14 19:33:16] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:33:30] Going home with 0 or less sidestep(s)!
[log] CLICK on L(80,350)@S(0)[0,0 1366x768]
[2016-08-14 19:33:36] At Home!
[2016-08-14 19:33:36] Are there returning expeditions to receive?
[2016-08-14 19:33:39] No, no fleets to receive!
[2016-08-14 19:33:40] Navigating to repair screen with 0 sidestep(s)!
[log] CLICK on L(112,434)@S(0)[0,0 1366x768]
[2016-08-14 19:33:46] Got invalid timer (21856)... trying again!
[2016-08-14 19:33:47] Got valid timer (01:21:55)!
[2016-08-14 19:33:48] Got valid timer (01:08:25)!
[2016-08-14 19:33:48] Got valid timer (00:50:01)!
[2016-08-14 19:33:48] Attempting to conduct repairs on 1 ship(s)!
[2016-08-14 19:33:48] Available docks: 1; repair queue: 1
[log] CLICK on L(252,273)@S(0)[0,0 1366x768]
[2016-08-14 19:33:52] Check for critically damaged ships.
[2016-08-14 19:33:55] Check for moderately-damaged ships.
[2016-08-14 19:33:58] 1 ships needing repairs left...
[2016-08-14 19:33:58] Available docks: 1; repair queue: 1
[log] CLICK on L(193,249)@S(0)[0,0 1366x768]
[2016-08-14 19:34:02] Check for critically damaged ships.
[2016-08-14 19:34:06] Check for moderately-damaged ships.
[log] CLICK on L(522,316)@S(0)[0,0 1366x768]
[2016-08-14 19:34:06] Starting repair on moderately damaged ship!
[2016-08-14 19:34:07] Using bucket for all repairs!
[log] CLICK on L(740,376)@S(0)[0,0 1366x768]
[log] CLICK on L(710,521)@S(0)[0,0 1366x768]
[log] CLICK on L(481,491)@S(0)[0,0 1366x768]
[2016-08-14 19:34:13] 0 ships needing repairs left...
[2016-08-14 19:34:13] Lets resupply fleets!
[2016-08-14 19:34:20] Navigating to resupply screen with 1 sidestep(s)!
[log] CLICK on L(23,452)@S(0)[0,0 1366x768]
[log] CLICK on L(30,280)@S(0)[0,0 1366x768]
[log] CLICK on L(117,212)@S(0)[0,0 1366x768]
[log] CLICK on L(180,207)@S(0)[0,0 1366x768]
[log] CLICK on L(128,204)@S(0)[0,0 1366x768]
[2016-08-14 19:34:37] Done resupplying!
[2016-08-14 19:34:37] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:34:53] Going home with 0 or less sidestep(s)!
[log] CLICK on L(82,307)@S(0)[0,0 1366x768]
[log] CLICK on L(66,365)@S(0)[0,0 1366x768]
[2016-08-14 19:35:06] At Home!
[2016-08-14 19:35:06] Are there returning expeditions to receive?
[2016-08-14 19:35:09] No, no fleets to receive!
[2016-08-14 19:35:09] Next sortie!: 2016-08-14 19:34:08
[2016-08-14 19:35:09] -----
[2016-08-14 19:35:09] Next expedition at 2016-08-14 19:30:40 (~4 expeditions conducted)
[2016-08-14 19:35:09] Next sortie at 2016-08-14 19:34:08 (~4 sorties conducted)
[2016-08-14 19:35:09] Next scheduled sleep at 2016-08-15 00:59:00
[2016-08-14 19:35:09] -----
[2016-08-14 19:35:35] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:35:43] At Home!
[2016-08-14 19:35:43] Checking for returning expeditions!
[2016-08-14 19:35:43] Are there returning expeditions to receive?
[2016-08-14 19:35:46] No, no fleets to receive!
[2016-08-14 19:35:46] Navigating to expedition menu with 1 sidestep(s)!
[log] CLICK on L(228,387)@S(0)[0,0 1366x768]
[log] CLICK on L(263,402)@S(0)[0,0 1366x768]
[log] CLICK on L(737,207)@S(0)[0,0 1366x768]
[2016-08-14 19:36:03] Let's send fleet 2 out for expedition 2!
[log] CLICK on L(461,293)@S(0)[0,0 1366x768]
[log] CLICK on L(711,543)@S(0)[0,0 1366x768]
[2016-08-14 19:36:07] Trying to send out fleet 2 for expedition 2
[2016-08-14 19:36:10] Checking expedition fleet status!
[log] CLICK on L(588,514)@S(0)[0,0 1366x768]
[2016-08-14 19:36:18] Expedition sent!: Expedition 2 (ETA 2016-08-14 20:05:33)
[2016-08-14 19:36:30] Focus on KanColle!
[log] App.focus KC3(0) #0
[2016-08-14 19:36:46] Going home with 0 or less sidestep(s)!
[log] CLICK on L(81,308)@S(0)[0,0 1366x768]
[2016-08-14 19:36:53] At Home!
[2016-08-14 19:36:53] Are there returning expeditions to receive?
[2016-08-14 19:36:56] No, no fleets to receive!
[2016-08-14 19:36:56] Navigating to combat menu with 1 sidestep(s)!
[log] CLICK on L(220,305)@S(0)[0,0 1366x768]
[log] CLICK on L(549,396)@S(0)[0,0 1366x768]
[log] CLICK on L(557,219)@S(0)[0,0 1366x768]
[log] CLICK on L(725,516)@S(0)[0,0 1366x768]
[log] CLICK on L(656,283)@S(0)[0,0 1366x768]
[log] CLICK on L(193,341)@S(0)[0,0 1366x768]
[log] CLICK on L(695,348)@S(0)[0,0 1366x768]
[log] CLICK on L(663,528)@S(0)[0,0 1366x768]
[2016-08-14 19:37:35] Checking fleet condition...
[2016-08-14 19:37:44] Light damage: 0; moderate damage: 0; critical damage: 0
[2016-08-14 19:37:50] Checking fleet morale!
[2016-08-14 19:37:56] Ships have good morale!
[2016-08-14 19:37:59] Commencing sortie!
[log] CLICK on L(695,524)@S(0)[0,0 1366x768]
[log] CLICK on L(659,201)@S(0)[0,0 1366x768]
[2016-08-14 19:38:23] Spinning compass!
[log] CLICK on L(680,421)@S(0)[0,0 1366x768]
[2016-08-14 19:38:53] Selecting fleet formation!
[log] CLICK on L(240,331)@S(0)[0,0 1366x768]
[2016-08-14 19:40:01] Checking fleet condition...
[2016-08-14 19:40:10] Light damage: 0; moderate damage: 0; critical damage: 0
[log] CLICK on L(596,221)@S(0)[0,0 1366x768]
[2016-08-14 19:40:28] Continuing on to next node...
[log] CLICK on L(287,303)@S(0)[0,0 1366x768]
[log] CLICK on L(738,230)@S(0)[0,0 1366x768]
[2016-08-14 19:40:52] Spinning compass!
[log] CLICK on L(626,420)@S(0)[0,0 1366x768]
[2016-08-14 19:41:23] Selecting fleet formation!
[log] CLICK on L(263,333)@S(0)[0,0 1366x768]
[2016-08-14 19:42:33] Checking fleet condition...
[2016-08-14 19:42:39] Light damage: 0; moderate damage: 1; critical damage: 0
[log] CLICK on L(168,208)@S(0)[0,0 1366x768]
[2016-08-14 19:42:55] Continuing on to next node...
[log] CLICK on L(314,300)@S(0)[0,0 1366x768]
[log] CLICK on L(479,267)@S(0)[0,0 1366x768]
[2016-08-14 19:43:22] Selecting fleet formation!
[2016-08-14 19:44:09] Declining night battle!
[log] CLICK on L(313,355)@S(0)[0,0 1366x768]
[log] CLICK on L(548,250)@S(0)[0,0 1366x768]
[2016-08-14 19:44:27] Checking fleet condition...
[2016-08-14 19:44:33] Light damage: 0; moderate damage: 1; critical damage: 0
[log] CLICK on L(162,208)@S(0)[0,0 1366x768]
[2016-08-14 19:44:50] Continuing on to next node...
[log] CLICK on L(314,295)@S(0)[0,0 1366x768]
[log] CLICK on L(619,168)@S(0)[0,0 1366x768]
[2016-08-14 19:45:14] Spinning compass!
[log] CLICK on L(644,434)@S(0)[0,0 1366x768]
[2016-08-14 19:45:44] Selecting fleet formation!

**Comment by AppleBoi86** [comment] 2016-08-14 11:00
Auto will stay put as shown in my screenshot.  No matter how long you wait, it just froze there until a click is done.  Only then everything will proceed as usual until the next sortie and getting stuck at the same screen.

i.imgur.com/TxuGX31.png

**Comment by stackhanovets** [comment] 2016-08-14 11:12
The script does an additional click every time? Really? I haven't noticed any. The boss screen keeps laughing every time. I've checked the cfg, but it was ok.

**Comment by mrmin123** [comment] 2016-08-14 11:32
@stackhanovets Yep. Note the `mouseDown` and `mouseUp`.

``` python
            # If formation select, select formation based on user config
            elif nodes_run < len(self.formations) and check_and_click(global_regions['formation_%s' % self.formations[nodes_run]], 'formation_%s.png' % self.formations[nodes_run]):
                # Now check for night battle prompt or post-battle report
                log_msg("Selecting fleet formation!")
                sleep(5)
                mouseDown(Button.LEFT)  # In case of boss monologue
                mouseUp()
                rejigger_mouse(self.kc_region, 50, 350, 0, 100)
                sleep(5)
                self.loop_post_formation()
                loop_pre_combat_stop = True
                break
```

After actually running through the map, I get the feeling that the code is fine, but the sleep before the mouse action might be too short? Or maybe it's clicking the wrong location, if there are deadzones for getting rid of the dialog screen. Needs further testing.

**Comment by mrmin123** [comment] 2016-08-14 11:45
Last update before I head to bed... I up'ed the sleep before the `mouseDown` to `sleep(8)` and it clicks through the dialog fine. The previous timing was too short I guess. Working change is in the 207_preboss_screen branch mentioned previously.

**Comment by mrmin123** [comment] 2016-08-14 17:27
Script successfully completed and farmed E-1 overnight. Merging code and closing this ticket.

**Closed as completed** 2016-08-14 17:28 UTC
Labels: bug
