### ISSUE TITLE
FleetComp Cycler (Needs testers)

### ISSUE THREAD

**Issue by waicool20** [mrmin123/kancolle-auto#351] opened 2017-03-29 18:07 UTC
### Kancolle Auto
I have picked up a feature request as requested in #86, pull request #350 , going on forth, admirals should be able to specify a list of fleet comps for the Combat module to cycle through. 

Expected behavior is that the script rotate fleet comps specified by ```FleetComps``` if more than one fleet comp is specified otherwise it should be identical to previous iterations of the script.

NOTE: ```FleetComp``` has been renamed to ```FleetComps``` in the config

For testers of the script download here: https://github.com/waicool20/kancolle-auto/archive/fleetcomp_cycler.zip

### KAGA

I have also updated KAGA to support the new configuration in this branch: 
https://github.com/waicool20/KAGA/tree/fleetcomps

NOTE: Existing profiles ```FleetComps``` will be set to nothing when first read due to the rename above. It's advised to configure it again and then save.

**Comment by waicool20** [comment] 2017-03-29 18:09
Download to a compiled KAGA snapshot of commit ad8af276f2ee64a670b0b1ffa1514cc739ae322d :

[KAGA_FleetCompCycler.zip](https://github.com/mrmin123/kancolle-auto/files/879924/KAGA_FleetCompCycler.zip)

**Comment by phantasia15** [comment] 2017-05-08 04:56
Tested this for a while.  

It does swapping fleets as intended. Although there was a problem when using together with SubmarineSwitch module.  

If one of the fleets contains a submarine being repaired and SubmarineSwitch is enabled than that fleet's sortie is canceled until the submarine is out of the dock. Basically, it happens like this: Switch to fleet 1 > go to sortie screen > check and find out a ship being repaired > go to dock and get some invalid timer, go to composition screen and swap out the submarine under repair > wait till next sortie > Switch to fleet 2 > ..... > Switch to fleet 1 and the same things happen again until the submarine is out of the dock.

**Comment by waicool20** [comment] 2017-05-08 05:58
Fleet 2 is sortieing normally right? Well I'm not sure what a good solution to this should be. As it is, I prefer it that way, as it'll continue to sortie fleet 2 until fleet 1 sub is out of the docks then fleet 1 is ready. The script does not track/cache per fleet ships/status so its pretty hard to determine when one of the fleet preset ships are ready.

**Comment by phantasia15** [comment] 2017-05-08 07:05
Yeah, Fleet 2 is sortieing normally.  

I think FleetComp Cycler is fine as it is. However, SubmarineSwitch module needs to be modified a bit  so that they can work together. When a damaged/under repair sub is found **before sortieing**, instead of swapping the subs **then ending the current cycle and waiting for next iteration**, SubmarineSwitch should swap out the sub and **continue** with the sortie.

**Comment by waicool20** [comment] 2017-05-08 07:57
Seems like a good solution overall even not considering the fleet comp cycler module, would be nice to have I guess, I'll look into it.

**Comment by mrmin123** [comment] 2017-06-01 03:48
PR is merged!

**Closed as completed by mrmin123** 2017-06-01 03:48 UTC
