### ISSUE TITLE
crashing during sortie causes infinite loop

### ISSUE THREAD

**Issue by perryhuynh** [mrmin123/kancolle-auto#40] opened 2015-10-11 12:59 UTC
often during the selection of the formation for 2nd (1st?,3rd+?) node, the script will crash possibly because it is still trying to look for the compass, would it be possible to add better support for auto restarting during a sortie?

**Comment by mrmin123** [comment] 2015-10-11 18:34
Odd, I've never seen the behavior you described. Could you post a relevant log if you get the chance? After selecting a formation, the script will ONLY look for the night battle or next buttons. If you're crashing at the formation select screen without selecting a formation, then I suspect that there are other issues at play.

Auto-recovery in a sortie will require a significant amount of work to implement and I don't think it's worth the time right now. My suggestion is to play through the rest of the sortie manually and then restart the script when you're back at home.

In the meantime I suggest trying out [this branch](https://github.com/mrmin123/kancolle-auto/tree/22_repairs) which may or may not help with the crashes you're seeing.

**Comment by perryhuynh** [comment] 2015-10-11 18:59
Yeah, I will post a log next time the issue occurs. The only time it ever occurs is crashing at formation select screen without selecting a formation.

**Comment by perryhuynh** [comment] 2015-10-11 19:37
[2015-10-12 04:23:42] Are there returning expeditions to receive?
[2015-10-12 04:23:46] No, no fleets to receive!
[2015-10-12 04:23:46] Navigating to Sortie menu!
[log] CLICK on L(240,356)@S(0)[0,0 1440x900]
[log] CLICK on L(274,326)@S(0)[0,0 1440x900]
[log] CLICK on L(419,529)@S(0)[0,0 1440x900]
[log] CLICK on L(301,437)@S(0)[0,0 1440x900]
[log] CLICK on L(726,531)@S(0)[0,0 1440x900]
[2015-10-12 04:24:04] Checking fleet condition...
[2015-10-12 04:24:09] Light damage: 3; moderate damage: 1; critical damage: 0
[2015-10-12 04:24:15] Checking fleet morale!
[2015-10-12 04:24:22] Ships have good morale!
[2015-10-12 04:24:25] Commencing sortie!
[log] CLICK on L(671,532)@S(0)[0,0 1440x900]
[log] CLICK on L(377,333)@S(0)[0,0 1440x900]
[2015-10-12 04:24:48] Spinning compass!
[log] CLICK on L(686,432)@S(0)[0,0 1440x900]
[2015-10-12 04:25:03] Selecting fleet formation!
[2015-10-12 04:25:59] Declining night battle!
[log] CLICK on L(333,327)@S(0)[0,0 1440x900]
[log] CLICK on L(794,519)@S(0)[0,0 1440x900]
[2015-10-12 04:26:15] Checking fleet condition...
[2015-10-12 04:26:20] Light damage: 3; moderate damage: 1; critical damage: 0
[log] CLICK on L(794,519)@S(0)[0,0 1440x900]
[log] CLICK on L(335,326)@S(0)[0,0 1440x900]
[log] CLICK on L(377,333)@S(0)[0,0 1440x900]
[2015-10-12 04:27:00] Spinning compass!
[error] script stopped with error in line 347
[error] FindFailed ( can not find next.png on the screen. )
[error] --- Traceback --- error source first
line: module ( function ) statement 
38: util (  wait_and_click )     kc_window.wait(pic, time)
128: combat (  go_sortie )     wait_and_click(self.kc_window, 'next.png', 30)
238: main (  sortie_action )     combat_item.go_sortie()
[error] --- Traceback --- end --------------
[2015-10-12 04:27:52] Reading config file
[2015-10-12 04:27:53] Expeditions enabled!
[2015-10-12 04:27:53] Combat enabled!
[2015-10-12 04:27:53] Config loaded!
[2015-10-12 04:27:53] Starting kancolle_auto
[2015-10-12 04:27:53] Focus on KanColle!
[log] App.focus Google Chrome(0) #0
[log] switchApp: Google Chrome

The only time it ever occurs is crashing at formation select screen without selecting a formation.
After that, it just loops trying to refocus on Google Chrome due to the focus function requiring the home button be there.

For the time being I've added a function to restart the entire game if it crashes so I should be able to bot without any issues

**Comment by mrmin123** [comment] 2015-10-12 04:46
I have to admit I have no idea how that issue is arising. After it spins the compass it'll look for another compass, formation button, combat_nb_retreat, next, or next_alt. Instead it goes directly to looking for a post-battle next button after somehow escaping loop_pre_combat and failing to find either next_alt or combat_nb_retreat.

Actually no, this could happen if in loop_pre_combat's while loop it finds the formation image (sure, since you're in the formation select screen), but fails to find it in the subsequent check_and_click (no idea why. Sikuli acting up?). Does it happen consistently at the same node? One possible solution I can think up of right now is to replace `Pattern('formation_%s.png' % self.formations[nodes_run]).exact()` with `Pattern('formation_%s.png' % self.formations[nodes_run]).similar(##)` with ## being some relatively high number, but this could cause another issue due to line_abreast and line_ahead being incredibly similar. Kind of hard to diagnose without being able to reproduce the problem, unfortunately.

**Comment by mrmin123** [comment] 2015-10-12 21:35
@perryhuynh You mentioned that you added a function to restart the entire game. I'm sure it's browser specific, but could you maybe share the code in a PR? It might be helpful to deal with catbombs and other crashes.

**Comment by perryhuynh** [comment] 2015-10-12 23:19
I essentially did the same thing as @kevin01523 in #46 

Did you still want me to provide code? And yeah I've only tested it on Google Chrome and it could possibly work on Chromium as well Using KC3, I just used the "Play via DMM Website" option and there is no reload confirmation pop up but I can add support for playing via DMM frame / API link if needed

**Comment by mrmin123** [comment] 2015-10-13 05:47
OK, I guess there might be enough of a value add with adding support for dealing with the catbombs especially in light of the recent changes with the API links timing out. I'll close this ticket and #46, and open up a separate one to consolidate efforts.

@perryhuynh if you'd like to provide code go for it, otherwise I'll implement it when I get the chance, since it does seem simple enough for some instances.

**Closed as completed by mrmin123** 2015-10-13 05:47 UTC
