### ISSUE TITLE
Expedition suddenly stop without errors.

### ISSUE THREAD

**Issue by AppleBoi86** [mrmin123/kancolle-auto#140] opened 2016-03-06 05:23 UTC
It just happened recently. There are no error or anything, it just stopped running for that particular expedition.

I ran expedition 
5 with fleet 2
21 with fleet 3
6 with fleet 4

After finish one run, fleet 4 just stop entirely while the other two just continue running without any errors. Any ideas of the caused?

**Comment by mrmin123** [comment] 2016-03-10 18:31
@AppleBoi86 What release are you on? Are you running sorties or PvP?

This used to happen previously when an expedition was returned in the middle of the sortie or PvP loop, but I think there are still holes somewhere. The expedition module needs to be reworked, anyway (again), so it might get fixed in the next release.

**Comment by AppleBoi86** [comment] 2016-03-11 02:06
I'm using the latest / current release.  And yes, I'm running sorties with expeditions.

**Comment by lhc-clover** [comment] 2016-03-11 04:06
I've got crashes on expedition too. My case is : start script with expedition returned (for example the first run of the day, unhandled expedition left on home).
I guess it is caused by expediton.py -> class Ensei. It don't have "end_time" property when init, which is called in kancolle_auto.py somewhere.
I will post error log later if needed.

**Comment by mrmin123** [comment] 2016-03-11 04:28
@AppleBoi86 ok, thanks for the clarification. I'll have to look at the combat loop a bit more carefully.
@lhc-clover that particular error will be fixed in the next release. If you want, you can use the [back_from_vacation](https://github.com/mrmin123/kancolle-auto/tree/back_from_vacation) branch, or the changes in the 2d458fc commit specifically.

**Comment by mrmin123** [comment] 2016-03-12 21:24
I _think_ this was fixed in the last update (7f52434). Please re-open if it crops up again.

**Closed as completed by mrmin123** 2016-03-12 21:24 UTC
Labels: bug
