### ISSUE TITLE
unable to send out combined fleet.

### ISSUE THREAD

**Issue by nekoma0** [mrmin123/kancolle-auto#317] opened 2017-02-24 14:45 UTC
* kancolle-auto version (date on first line of your CHANGELOG.md):
* Viewer/browser: ING Client(it's a chinese client)
* Operating system: Windows 7 in VirtualBox

#### Issue
Everyone is working perfectly i mean sortie on E1 as well.
But Combined fleet seems to be failing and ending in a recovery loop which i dont understand why.
When ever fleet is going into Sortie, it will fail and entering basic recovery.

![image](https://cloud.githubusercontent.com/assets/21262949/23307385/adf98a96-faea-11e6-9e7d-afdb41813892.png)

**Comment by mrmin123** [comment] 2017-02-24 17:37
The script seems to be failing at the point where it clicks the sortie
start button. Is your LBAS setup configured correctly? If LBAS is enabled
for kancolle-auto, the sortie start button it looks for is different from
if it is disabled.

**Comment by nekoma0** [comment] 2017-02-24 20:45
LBAS is disabled on both kancolle bot config as well as in game

**Comment by mrmin123** [comment] 2017-02-24 22:18
OK, could be due to the wait timer changes (#309). Will attempt to reproduce.

**Comment by mrmin123** [comment] 2017-02-25 01:15
I couldn't reproduce..:
![image](https://cloud.githubusercontent.com/assets/4326866/23326633/72063178-fab4-11e6-92ff-b5b773c06c97.png)
Sorties successfully and continued on w/ LBAS disabled in-game and in-config... Can you post in the screen you see on failure in your viewer?

**Comment by nekoma0** [comment] 2017-02-25 10:55
ok something weird just happen, i just booted vitualbox and reopen everything, and doublecheck everything is unchanged while trying to post a screen of what you're guiding me to do so. And it works.

Previously, i was failing on E2 having the above issue that i mentioned. but nonetheless, i cleared it manually, and did not reboot.

after that, i cleared E3, and copy pasta the event config from wiki, while disabling everything else, and it did not work. but now it did. weird.

do you want me to post E2 side where the script failed with LBAS?

**Comment by mrmin123** [comment] 2017-02-25 19:38
Sure. As a side note, I think running on VM sometimes does cause issues. See issue #10

**Comment by mrmin123** [comment] 2017-03-01 06:19
Closing for now.

**Closed as completed by mrmin123** 2017-03-01 06:19 UTC
